export type VerificationFlag = "RC Verified" | "Yard Verified" | "Photos Verified";

export type Vehicle = {
  id: string;
  title: string;
  type: "Truck" | "Tipper" | "Pickup" | "Bus" | "Trailer" | "Tractor";
  brand: string;
  model: string;
  year: number;
  kmDriven: number;
  fuelType: "Diesel" | "CNG";
  axleType: string;
  registrationState: string;
  city: string;
  state: string;
  image: string;
  gallery: string[];
  financeCompany: string;
  price: number;
  reservePrice: number;
  repoStatus: "Bank Seized" | "Auction Live" | "Ready For Sale";
  sellerType: "Bank Agent" | "Yard Partner";
  sellerName: string;
  sellerRole: string;
  sellerPhone: string;
  condition: "Running" | "Non-running";
  conditionNotes: string;
  accidentNotes: string;
  auctionDate: string;
  yardLocation: string;
  verifiedBadges: VerificationFlag[];
  inspectionNotes: string[];
  inquiries: number;
  listingStatus?: "Pending" | "Verified" | "Rejected" | "Sold";
};
