import type { DbVehicle } from "./schema";
import type { Vehicle } from "@/types/vehicle";
import { sanitizeSupabaseMediaArray, sanitizeSupabaseMediaUrl } from "@/lib/media";
import {
  normalizeClassification,
  normalizeListingMode,
} from "@/lib/vehicle-classification";

/**
 * Maps a database row (DbVehicle) to the application's Vehicle shape,
 * converting numeric string fields from postgres to numbers.
 */
export function dbToVehicle(row: DbVehicle): Vehicle {
  const trustBadges: Vehicle["verifiedBadges"] = [];
  if (row.rcVerified) trustBadges.push("RC Verified");
  if (row.photosVerified) trustBadges.push("Photos Verified");
  if (row.yardVerified) trustBadges.push("Yard Verified");
  const image = sanitizeSupabaseMediaUrl(row.image);
  const gallery = sanitizeSupabaseMediaArray(row.gallery);
  const normalizedImage = image || gallery[0] || "";
  const classification = normalizeClassification({
    assetStructure: row.assetStructure,
    detachableType: row.detachableType,
    assetConfiguration: row.assetConfiguration,
  });

  return {
    id: row.id,
    sellerId: row.sellerId,
    createdByUserId: row.createdByUserId,
    listingType: row.listingType,
    listingMode: normalizeListingMode(row.listingMode),
    assetConfiguration: (row.assetConfiguration || "Complete Vehicle") as Vehicle["assetConfiguration"],
    assetStructure: classification.assetStructure,
    detachableType: classification.detachableType,
    status: row.status,
    title: row.title,
    type: row.type as Vehicle["type"],
    assetCategory: row.assetCategory || row.type,
    vehicleSubType: row.vehicleSubType,
    bodyApplicationType: row.bodyApplicationType || row.vehicleSubType || row.bodyType,
    brand: row.brand,
    model: row.model,
    year: row.year,
    isRegistered: row.isRegistered,
    kmDriven: row.kmDriven,
    vehicleRegistrationNumber: row.vehicleRegistrationNumber,
    kmMeterStatus: row.kmMeterStatus,
    runningCondition: row.runningCondition,
    fuelType: row.fuelType as Vehicle["fuelType"],
    bsNorm: row.bsNorm,
    transmission: row.transmission,
    axleConfiguration: row.axleConfiguration || row.axleType,
    horsepower: row.horsepower,
    odometerReading: row.odometerReading,
    hourMeterReading: row.hourMeterReading,
    axleType: row.axleType,
    numberOfAxles: row.numberOfAxles,
    bodyType: row.bodyType,
    bodyLength: row.bodyLength,
    bodyDimensions: row.bodyDimensions,
    payloadCapacity: row.payloadCapacity,
    bodyAttached: row.bodyAttached,
    bodyCondition: row.bodyCondition,
    trailerType: row.trailerType,
    trailerLength: row.trailerLength,
    trailerManufacturer: row.trailerManufacturer,
    trailerManufacturingMonthYear: row.trailerManufacturingMonthYear,
    suspensionType: row.suspensionType,
    tyreInspectionReport: row.tyreInspectionReport,
    tyreCount: row.tyreCount,
    currentTyreCount: row.currentTyreCount,
    tyreCondition: row.tyreCondition,
    registrationState: row.registrationState,
    city: row.city,
    state: row.state,
    vehicleOrYardLocation: row.vehicleOrYardLocation,
    image: normalizedImage,
    gallery,
    frontPhoto: sanitizeSupabaseMediaUrl(row.frontPhoto) || undefined,
    backPhoto: sanitizeSupabaseMediaUrl(row.backPhoto) || undefined,
    sidePhoto: sanitizeSupabaseMediaUrl(row.sidePhoto) || undefined,
    leftSidePhoto:
      sanitizeSupabaseMediaUrl(row.leftSidePhoto) ||
      sanitizeSupabaseMediaUrl(row.sidePhoto) ||
      undefined,
    rightSidePhoto: sanitizeSupabaseMediaUrl(row.rightSidePhoto) || undefined,
    interiorPhoto: sanitizeSupabaseMediaUrl(row.interiorPhoto) || undefined,
    walkaroundVideo: sanitizeSupabaseMediaUrl(row.walkaroundVideo) || null,
    engineStartUpVideo: sanitizeSupabaseMediaUrl(row.engineStartUpVideo) || null,
    financeCompany: row.financeCompany,
    bankInstitutionName: row.bankInstitutionName,
    branchName: row.branchName,
    price: Number(row.price),
    expectedPrice: Number(row.expectedPrice),
    reservePrice: Number(row.reservePrice),
    repoStatus: row.repoStatus as Vehicle["repoStatus"],
    sellerType: row.sellerType as Vehicle["sellerType"],
    sellerName: row.sellerName,
    sellerRole: row.sellerRole,
    sellerPhone: row.sellerPhone,
    alternateContactNumber: row.alternateContactNumber,
    alternateContactNumberVerified: row.alternateContactNumberVerified,
    businessName: row.businessName,
    gstin: row.gstin,
    condition: row.condition as Vehicle["condition"],
    conditionNotes: row.conditionNotes,
    engineCondition: row.engineCondition,
    needsTowing: row.needsTowing,
    roadSafeStatus: row.roadSafeStatus,
    accidentNotes: row.accidentNotes,
    auctionDate: row.auctionDate,
    yardName: row.yardName,
    yardContact: row.yardContact,
    yardLocation: row.yardLocation,
    taxDue: row.taxDue,
    challans: row.challans,
    insuranceExpiry: row.insuranceExpiry,
    fitnessExpiry: row.fitnessExpiry,
    permitExpiry: row.permitExpiry,
    nocStatus: row.nocStatus,
    machineSerialNumber: row.machineSerialNumber,
    engineNumber: row.engineNumber,
    chassisNumber: row.chassisNumber,
    trailerNumber: row.trailerNumber,
    gvwTonnes: row.gvwTonnes,
    gpsInstalled: row.gpsInstalled,
    abs: row.abs,
    batteryAvailable: row.batteryAvailable,
    keyAvailable: row.keyAvailable,
    acCabin: row.acCabin,
    tyresIncluded: row.tyresIncluded,
    rimsDiscsIncluded: row.rimsDiscsIncluded,
    batteryIncluded: row.batteryIncluded,
    cabinAvailable: row.cabinAvailable,
    engineAvailable: row.engineAvailable,
    documentsAvailable: row.documentsAvailable,
    remarks: row.remarks,
    fleetManagementSoftwareAvailable: row.fleetManagementSoftwareAvailable,
    verifiedBadges: trustBadges,
    rcVerified: row.rcVerified,
    photosVerified: row.photosVerified,
    yardVerified: row.yardVerified,
    sellerVerified: row.sellerVerified,
    isPublished: row.isPublished,
    verificationStatus: row.verificationStatus,
    rejectionReason: row.rejectionReason,
    verifiedBy: row.verifiedBy,
    verifiedAt: row.verifiedAt ? row.verifiedAt.toISOString() : null,
    soldAt: row.soldAt ? row.soldAt.toISOString() : null,
    deletedAt: row.deletedAt ? row.deletedAt.toISOString() : null,
    missingPhotos: row.missingPhotos,
    priceTooLow: row.priceTooLow,
    duplicateRegistration: row.duplicateRegistration,
    newSeller: row.newSeller,
    missingYardLocation: row.missingYardLocation,
    inspectionNotes: row.inspectionNotes as string[],
    inquiries: row.inquiries,
    listingStatus: row.listingStatus as Vehicle["listingStatus"],
  };
}
