import type { DbVehicle } from "./schema";
import type { Vehicle } from "@/types/vehicle";

/**
 * Maps a database row (DbVehicle) to the application's Vehicle shape,
 * converting numeric string fields from postgres to numbers.
 */
export function dbToVehicle(row: DbVehicle): Vehicle {
  const trustBadges: Vehicle["verifiedBadges"] = [];
  if (row.rcVerified) trustBadges.push("RC Verified");
  if (row.photosVerified) trustBadges.push("Photos Verified");
  if (row.yardVerified) trustBadges.push("Yard Verified");

  return {
    id: row.id,
    sellerId: row.sellerId,
    createdByUserId: row.createdByUserId,
    listingType: row.listingType,
    assetConfiguration: (row.assetConfiguration || "Complete Vehicle") as Vehicle["assetConfiguration"],
    status: row.status,
    title: row.title,
    type: row.type as Vehicle["type"],
    vehicleSubType: row.vehicleSubType,
    brand: row.brand,
    model: row.model,
    year: row.year,
    kmDriven: row.kmDriven,
    vehicleRegistrationNumber: row.vehicleRegistrationNumber,
    kmMeterStatus: row.kmMeterStatus,
    runningCondition: row.runningCondition,
    fuelType: row.fuelType as Vehicle["fuelType"],
    axleType: row.axleType,
    numberOfAxles: row.numberOfAxles,
    bodyType: row.bodyType,
    bodyDimensions: row.bodyDimensions,
    trailerType: row.trailerType,
    trailerLength: row.trailerLength,
    trailerManufacturer: row.trailerManufacturer,
    trailerManufacturingMonthYear: row.trailerManufacturingMonthYear,
    suspensionType: row.suspensionType,
    tyreInspectionReport: row.tyreInspectionReport,
    tyreCount: row.tyreCount,
    currentTyreCount: row.currentTyreCount,
    tyreCondition: row.tyreCondition,
    registrationState: row.registrationState,
    city: row.city,
    state: row.state,
    vehicleOrYardLocation: row.vehicleOrYardLocation,
    image: row.image,
    gallery: row.gallery as string[],
    frontPhoto: row.frontPhoto,
    backPhoto: row.backPhoto,
    sidePhoto: row.sidePhoto,
    interiorPhoto: row.interiorPhoto,
    walkaroundVideo: row.walkaroundVideo,
    engineStartUpVideo: row.engineStartUpVideo,
    financeCompany: row.financeCompany,
    bankInstitutionName: row.bankInstitutionName,
    branchName: row.branchName,
    price: Number(row.price),
    expectedPrice: Number(row.expectedPrice),
    reservePrice: Number(row.reservePrice),
    repoStatus: row.repoStatus as Vehicle["repoStatus"],
    sellerType: row.sellerType as Vehicle["sellerType"],
    sellerName: row.sellerName,
    sellerRole: row.sellerRole,
    sellerPhone: row.sellerPhone,
    alternateContactNumber: row.alternateContactNumber,
    businessName: row.businessName,
    gstin: row.gstin,
    condition: row.condition as Vehicle["condition"],
    conditionNotes: row.conditionNotes,
    engineCondition: row.engineCondition,
    needsTowing: row.needsTowing,
    roadSafeStatus: row.roadSafeStatus,
    accidentNotes: row.accidentNotes,
    auctionDate: row.auctionDate,
    yardName: row.yardName,
    yardContact: row.yardContact,
    yardLocation: row.yardLocation,
    taxDue: row.taxDue,
    challans: row.challans,
    insuranceExpiry: row.insuranceExpiry,
    fitnessExpiry: row.fitnessExpiry,
    permitExpiry: row.permitExpiry,
    nocStatus: row.nocStatus,
    engineNumber: row.engineNumber,
    chassisNumber: row.chassisNumber,
    trailerNumber: row.trailerNumber,
    gvwTonnes: row.gvwTonnes,
    gpsInstalled: row.gpsInstalled,
    abs: row.abs,
    fleetManagementSoftwareAvailable: row.fleetManagementSoftwareAvailable,
    verifiedBadges: trustBadges,
    rcVerified: row.rcVerified,
    photosVerified: row.photosVerified,
    yardVerified: row.yardVerified,
    sellerVerified: row.sellerVerified,
    isPublished: row.isPublished,
    verificationStatus: row.verificationStatus,
    rejectionReason: row.rejectionReason,
    verifiedBy: row.verifiedBy,
    verifiedAt: row.verifiedAt ? row.verifiedAt.toISOString() : null,
    soldAt: row.soldAt ? row.soldAt.toISOString() : null,
    missingPhotos: row.missingPhotos,
    priceTooLow: row.priceTooLow,
    duplicateRegistration: row.duplicateRegistration,
    newSeller: row.newSeller,
    missingYardLocation: row.missingYardLocation,
    inspectionNotes: row.inspectionNotes as string[],
    inquiries: row.inquiries,
    listingStatus: row.listingStatus as Vehicle["listingStatus"],
  };
}
