import type { Vehicle } from "@/lib/types";

const now = new Date().toISOString();

export const seedVehicles: Vehicle[] = [
  {
    id: "tata-407-1",
    title: "Tata 407 - 2019",
    vehicleType: "LCV",
    brand: "Tata",
    model: "407 Gold SFC",
    year: 2019,
    registrationState: "MH",
    price: 540000,
    financeCompany: "HDFC Bank",
    city: "Pune",
    state: "Maharashtra",
    yardLocation: "Wagholi Recovery Yard",
    condition: "Running condition, light denting on front bumper.",
    status: "VERIFIED",
    verificationStatus: "VERIFIED",
    sellerName: "Rakesh Motors",
    sellerPhone: "919876543210",
    images: ["/vehicles/tata-407.svg"],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "ashok-tipper-1",
    title: "Ashok Leyland Tipper - 2018",
    vehicleType: "Tipper",
    brand: "Ashok Leyland",
    model: "1618 Tipper",
    year: 2018,
    registrationState: "GJ",
    price: 1120000,
    financeCompany: "Shriram Finance",
    city: "Surat",
    state: "Gujarat",
    yardLocation: "Kamrej Stock Yard",
    condition: "Engine starts well, tyre wear around 35%.",
    status: "VERIFIED",
    verificationStatus: "VERIFIED",
    sellerName: "Kailash Recovery",
    sellerPhone: "919812340000",
    images: ["/vehicles/ashok-leyland-tipper.svg"],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "bharatbenz-truck-1",
    title: "BharatBenz Truck - 2020",
    vehicleType: "Truck",
    brand: "BharatBenz",
    model: "2823R",
    year: 2020,
    registrationState: "KA",
    price: 1780000,
    financeCompany: "Bajaj Finserv",
    city: "Bengaluru",
    state: "Karnataka",
    yardLocation: "Nelamangala Commercial Yard",
    condition: "Single owner, cabin clean, battery recently replaced.",
    status: "PENDING",
    verificationStatus: "UNVERIFIED",
    sellerName: "S M Commercials",
    sellerPhone: "919900112233",
    images: ["/vehicles/bharatbenz-truck.svg"],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "bolero-pickup-1",
    title: "Mahindra Bolero Pickup - 2021",
    vehicleType: "Pickup",
    brand: "Mahindra",
    model: "Bolero Pik-Up ExtraLong",
    year: 2021,
    registrationState: "UP",
    price: 690000,
    financeCompany: "Mahindra Finance",
    city: "Lucknow",
    state: "Uttar Pradesh",
    yardLocation: "Amausi Yard",
    condition: "Body straight, clutch plate requires inspection.",
    status: "VERIFIED",
    verificationStatus: "VERIFIED",
    sellerName: "Prime Auto Associates",
    sellerPhone: "918882221111",
    images: ["/vehicles/mahindra-bolero-pickup.svg"],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "eicher-pro-1",
    title: "Eicher Pro Truck - 2017",
    vehicleType: "Truck",
    brand: "Eicher",
    model: "Pro 3015",
    year: 2017,
    registrationState: "TN",
    price: 840000,
    financeCompany: "Tata Capital",
    city: "Chennai",
    state: "Tamil Nadu",
    yardLocation: "Poonamallee Repo Hub",
    condition: "Needs repainting, mechanically inspected last month.",
    status: "PENDING",
    verificationStatus: "UNVERIFIED",
    sellerName: "Velan Fleet Services",
    sellerPhone: "919840000777",
    images: ["/vehicles/eicher-pro-truck.svg"],
    createdAt: now,
    updatedAt: now,
  },
];
